version: '3.8'

services:
  db:
    image: mysql:8.0
    env_file: .env
    volumes:
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  api:
    build:
      context: ./server
      dockerfile: DockerfilePython
    env_file: .env
    command: uvicorn server:app --host ${PYTHON_HOST} --port ${PYTHON_PORT}
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: dockerfileReact
    env_file: .env
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    depends_on:
      - api
